# Generated by Django 4.1.1 on 2022-10-11 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClaseCuenta',
            fields=[
                ('id_clase_cuenta', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='id_clase_cuenta')),
                ('nombre_clase_cuenta', models.CharField(max_length=40, verbose_name='nombre_clase_cuenta')),
                ('codigo_clase_cuenta', models.CharField(max_length=1, verbose_name='codigo_clase_cuenta')),
            ],
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id_cuenta', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='id_cuenta')),
                ('nombre_cuenta', models.CharField(max_length=40, verbose_name='nombre_cuenta')),
                ('codigo_cuenta', models.CharField(max_length=3, verbose_name='codigo_cuenta')),
            ],
        ),
        migrations.CreateModel(
            name='CuentaT',
            fields=[
                ('id_cuenta_T', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='id_cuenta_T')),
                ('saldo_cuenta_T', models.FloatField(verbose_name='saldo_cuenta_T')),
            ],
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id_partida', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='id_partida')),
                ('fecha_partida', models.DateTimeField(auto_now_add=True, null=True)),
                ('descripcion_partida', models.CharField(max_length=350, null=True)),
                ('numero_partida', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoRegistro',
            fields=[
                ('id_tipo_registro', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='id_tipo_regsitro')),
                ('nombre_tipo_registro', models.CharField(max_length=5, verbose_name='nombre_tipo_registro')),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id_registro', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='id_registro')),
                ('monto', models.FloatField(verbose_name='monto')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='modulo_general.cuenta')),
                ('libro_mayor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='modulo_general.cuentat')),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='modulo_general.partida', verbose_name='partida')),
                ('tipo_registro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='modulo_general.tiporegistro')),
            ],
        ),
        migrations.CreateModel(
            name='GrupoCuenta',
            fields=[
                ('id_grupo_cuenta', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='id_grupo_cuenta')),
                ('nombre_grupo_cuenta', models.CharField(max_length=40, verbose_name='nombre_grupo_cuenta')),
                ('codigo_grupo_cuenta', models.CharField(max_length=2, verbose_name='codigo_grupo_cuenta')),
                ('clase_cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='modulo_general.clasecuenta')),
            ],
        ),
        migrations.AddField(
            model_name='cuenta',
            name='grupo_cuenta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='modulo_general.grupocuenta', verbose_name='grupo_cuenta'),
        ),
    ]
