# Generated by Django 4.1.1 on 2022-10-18 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_general', '0004_alter_partida_fecha_partida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partida',
            name='fecha_partida',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
