# Generated by Django 4.1.1 on 2022-10-21 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_general', '0006_alter_registro_partida_balancecomprobacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentat',
            name='cuenta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='modulo_general.cuenta'),
        ),
    ]
