# Generated by Django 4.1.1 on 2022-10-21 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_general', '0008_alter_cuenta_grupo_cuenta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentat',
            name='libro_mayor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='modulo_general.libromayor'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='cuenta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_general.cuenta'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='tipo_registro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_general.tiporegistro'),
        ),
    ]
