# Generated by Django 4.1.1 on 2022-10-21 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_general', '0010_balancecomprobacion_esta_ajustado_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partida',
            old_name='es_partidad_ajuste',
            new_name='es_partida_ajuste',
        ),
    ]
