# Generated by Django 4.1.1 on 2022-10-23 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_general', '0011_rename_es_partidad_ajuste_partida_es_partida_ajuste'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoResultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utilidad', models.FloatField(verbose_name='utilidad')),
                ('balance_comprobacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_general.balancecomprobacion')),
            ],
        ),
        migrations.CreateModel(
            name='EstadoCapital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservas', models.FloatField()),
                ('capital_social', models.FloatField()),
                ('balance_comprobacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_general.balancecomprobacion')),
            ],
        ),
        migrations.CreateModel(
            name='BalanceGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo_debe', models.FloatField()),
                ('saldo_haber', models.FloatField()),
                ('balance_comprobacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_general.balancecomprobacion')),
            ],
        ),
    ]
