# Generated by Django 4.1.1 on 2022-10-23 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_general', '0012_estadoresultado_estadocapital_balancegeneral'),
    ]

    operations = [
        migrations.AddField(
            model_name='balancegeneral',
            name='fecha_de_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='balancegeneral',
            name='fecha_de_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estadocapital',
            name='fecha_de_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estadocapital',
            name='fecha_de_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estadoresultado',
            name='fecha_de_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estadoresultado',
            name='fecha_de_inicio',
            field=models.DateField(blank=True, null=True),
        ),
    ]
