# Generated by Django 4.0.5 on 2022-11-13 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenidad',
            fields=[
                ('amenidad_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_amenidad', models.CharField(max_length=1024)),
            ],
            options={
                'db_table': 'amenidad',
            },
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('ciudad_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_ciudad', models.CharField(max_length=1024)),
            ],
            options={
                'db_table': 'ciudad',
            },
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('foto_id', models.AutoField(primary_key=True, serialize=False)),
                ('foto_lugar', models.CharField(max_length=1024)),
            ],
            options={
                'db_table': 'foto',
            },
        ),
        migrations.CreateModel(
            name='Hobbie',
            fields=[
                ('hobbie_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_hobbie', models.CharField(max_length=1024)),
            ],
            options={
                'db_table': 'hobbie',
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('pais_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_pais', models.CharField(max_length=1024)),
            ],
            options={
                'db_table': 'pais',
            },
        ),
        migrations.CreateModel(
            name='PerfilUser',
            fields=[
                ('perfil_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=1024)),
                ('passwrd', models.CharField(max_length=1024)),
                ('nombre_user', models.CharField(max_length=1024)),
                ('apellidos_user', models.CharField(max_length=1024)),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('biografia', models.CharField(blank=True, max_length=1024, null=True)),
                ('telefono', models.CharField(blank=True, max_length=1024, null=True)),
                ('username', models.CharField(max_length=1024)),
                ('user_facebook', models.CharField(blank=True, max_length=1024, null=True)),
                ('user_insta', models.CharField(blank=True, max_length=1024, null=True)),
                ('user_twitter', models.CharField(blank=True, max_length=1024, null=True)),
                ('foto_perfil', models.CharField(blank=True, max_length=1024, null=True)),
                ('genero', models.CharField(max_length=1024)),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cherooms.ciudad')),
            ],
            options={
                'db_table': 'perfil_user',
            },
        ),
        migrations.CreateModel(
            name='Preferencia',
            fields=[
                ('preferencia_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_preferencia', models.CharField(max_length=1024)),
            ],
            options={
                'db_table': 'preferencia',
            },
        ),
        migrations.CreateModel(
            name='PublicacionAlquiler',
            fields=[
                ('publicacion_id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=1024)),
                ('descrip_lugar', models.CharField(max_length=1024)),
                ('coordenadas', models.CharField(max_length=1024)),
                ('num_ocupantes', models.IntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('tiempo_contrato', models.CharField(max_length=1024)),
                ('fecha_publi', models.DateField()),
                ('p_activa', models.BooleanField()),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cherooms.perfiluser')),
            ],
            options={
                'db_table': 'publicacion_alquiler',
            },
        ),
        migrations.CreateModel(
            name='VentaAlquiler',
            fields=[
                ('venta_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_venta', models.DateField()),
                ('comision', models.DecimalField(decimal_places=2, max_digits=8)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cherooms.perfiluser')),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cherooms.publicacionalquiler')),
            ],
            options={
                'db_table': 'venta_alquiler',
            },
        ),
        migrations.CreateModel(
            name='ListaPreferencia',
            fields=[
                ('listapref_id', models.AutoField(primary_key=True, serialize=False)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cherooms.perfiluser')),
                ('preferencia', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cherooms.preferencia')),
            ],
            options={
                'db_table': 'lista_preferencia',
            },
        ),
        migrations.CreateModel(
            name='ListaFotos',
            fields=[
                ('listafoto_id', models.AutoField(primary_key=True, serialize=False)),
                ('foto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cherooms.foto')),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cherooms.publicacionalquiler')),
            ],
            options={
                'db_table': 'lista_fotos',
            },
        ),
        migrations.CreateModel(
            name='Listadohobbies',
            fields=[
                ('listhobbies_id', models.AutoField(primary_key=True, serialize=False)),
                ('hobbie', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cherooms.hobbie')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cherooms.perfiluser')),
            ],
            options={
                'db_table': 'listadohobbies',
            },
        ),
        migrations.CreateModel(
            name='ListaAmenidad',
            fields=[
                ('listamenidad_id', models.AutoField(primary_key=True, serialize=False)),
                ('amenidad', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cherooms.amenidad')),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cherooms.publicacionalquiler')),
            ],
            options={
                'db_table': 'lista_amenidad',
            },
        ),
        migrations.CreateModel(
            name='HistorialBusqueda',
            fields=[
                ('busqueda_id', models.AutoField(primary_key=True, serialize=False)),
                ('busqueda', models.CharField(max_length=1024)),
                ('fecha_busqueda', models.DateField()),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cherooms.perfiluser')),
            ],
            options={
                'db_table': 'historial_busqueda',
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('departamento_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_depa', models.CharField(max_length=1024)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cherooms.pais')),
            ],
            options={
                'db_table': 'departamento',
            },
        ),
        migrations.AddField(
            model_name='ciudad',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cherooms.departamento'),
        ),
        migrations.CreateModel(
            name='Cheros',
            fields=[
                ('cheros_id', models.AutoField(primary_key=True, serialize=False)),
                ('favorito_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='favorito', to='cherooms.perfiluser')),
                ('perfil_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='perfil', to='cherooms.perfiluser')),
            ],
            options={
                'db_table': 'cheros',
            },
        ),
    ]
