# Generated by Django 4.0.5 on 2022-11-13 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cherooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciudad',
            name='departamento',
            field=models.ForeignKey(db_column='departamento_id', on_delete=django.db.models.deletion.DO_NOTHING, to='cherooms.departamento'),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='pais',
            field=models.ForeignKey(db_column='pais_id', on_delete=django.db.models.deletion.DO_NOTHING, to='cherooms.pais'),
        ),
        migrations.AlterField(
            model_name='historialbusqueda',
            name='perfil',
            field=models.ForeignKey(db_column='perfil_id', on_delete=django.db.models.deletion.DO_NOTHING, to='cherooms.perfiluser'),
        ),
        migrations.AlterField(
            model_name='listaamenidad',
            name='amenidad',
            field=models.ForeignKey(db_column='amenidad_id', on_delete=django.db.models.deletion.DO_NOTHING, to='cherooms.amenidad'),
        ),
        migrations.AlterField(
            model_name='listaamenidad',
            name='publicacion',
            field=models.ForeignKey(db_column='publicacion_id', on_delete=django.db.models.deletion.DO_NOTHING, to='cherooms.publicacionalquiler'),
        ),
        migrations.AlterField(
            model_name='listadohobbies',
            name='hobbie',
            field=models.ForeignKey(db_column='hobbie_id', on_delete=django.db.models.deletion.DO_NOTHING, to='cherooms.hobbie'),
        ),
        migrations.AlterField(
            model_name='listadohobbies',
            name='perfil',
            field=models.ForeignKey(db_column='perfil_id', on_delete=django.db.models.deletion.DO_NOTHING, to='cherooms.perfiluser'),
        ),
        migrations.AlterField(
            model_name='listafotos',
            name='foto',
            field=models.ForeignKey(db_column='foto_id', on_delete=django.db.models.deletion.DO_NOTHING, to='cherooms.foto'),
        ),
        migrations.AlterField(
            model_name='listafotos',
            name='publicacion',
            field=models.ForeignKey(db_column='publicacion_id', on_delete=django.db.models.deletion.DO_NOTHING, to='cherooms.publicacionalquiler'),
        ),
        migrations.AlterField(
            model_name='listapreferencia',
            name='perfil',
            field=models.ForeignKey(db_column='perfil_id', on_delete=django.db.models.deletion.DO_NOTHING, to='cherooms.perfiluser'),
        ),
        migrations.AlterField(
            model_name='listapreferencia',
            name='preferencia',
            field=models.ForeignKey(db_column='preferencia_id', on_delete=django.db.models.deletion.DO_NOTHING, to='cherooms.preferencia'),
        ),
        migrations.AlterField(
            model_name='perfiluser',
            name='ciudad',
            field=models.ForeignKey(db_column='ciudad_id', on_delete=django.db.models.deletion.DO_NOTHING, to='cherooms.ciudad'),
        ),
        migrations.AlterField(
            model_name='publicacionalquiler',
            name='perfil',
            field=models.ForeignKey(db_column='perfil_id', on_delete=django.db.models.deletion.DO_NOTHING, to='cherooms.perfiluser'),
        ),
        migrations.AlterField(
            model_name='ventaalquiler',
            name='perfil',
            field=models.ForeignKey(db_column='perfil_id', on_delete=django.db.models.deletion.DO_NOTHING, to='cherooms.perfiluser'),
        ),
        migrations.AlterField(
            model_name='ventaalquiler',
            name='publicacion',
            field=models.ForeignKey(db_column='publicacion_id', on_delete=django.db.models.deletion.DO_NOTHING, to='cherooms.publicacionalquiler'),
        ),
    ]
