# Generated by Django 4.1.3 on 2022-11-19 17:19

import cherooms.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cherooms', '0002_alter_ciudad_departamento_alter_departamento_pais_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto',
            name='foto_lugar',
            field=models.ImageField(blank=True, null=True, upload_to=cherooms.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='historialbusqueda',
            name='fecha_busqueda',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 19, 11, 19, 42, 651355)),
        ),
    ]
