# Generated by Django 4.1.3 on 2022-11-19 22:26

import cherooms.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cherooms', '0004_alter_historialbusqueda_fecha_busqueda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfiluser',
            name='passwrd',
        ),
        migrations.AddField(
            model_name='perfiluser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='perfiluser',
            name='password',
            field=models.CharField(default=None, max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfiluser',
            name='usuario_administrador',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='historialbusqueda',
            name='fecha_busqueda',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 19, 16, 26, 47, 106510)),
        ),
        migrations.AlterField(
            model_name='perfiluser',
            name='email',
            field=models.CharField(max_length=1024, unique=True),
        ),
        migrations.AlterField(
            model_name='perfiluser',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to=cherooms.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='perfiluser',
            name='username',
            field=models.CharField(max_length=1024, unique=True),
        ),
    ]
