# Generated by Django 4.1.3 on 2022-11-19 22:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cherooms', '0007_alter_historialbusqueda_fecha_busqueda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialbusqueda',
            name='fecha_busqueda',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 19, 16, 35, 46, 843008)),
        ),
    ]
