# Generated by Django 4.1.3 on 2022-11-19 22:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cherooms', '0009_alter_historialbusqueda_fecha_busqueda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialbusqueda',
            name='fecha_busqueda',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 19, 16, 39, 33, 536583)),
        ),
        migrations.AlterField(
            model_name='perfiluser',
            name='ciudad',
            field=models.ForeignKey(blank=True, db_column='ciudad_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cherooms.ciudad'),
        ),
    ]
