# Generated by Django 4.1.3 on 2022-11-19 22:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cherooms', '0010_alter_historialbusqueda_fecha_busqueda_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialbusqueda',
            name='fecha_busqueda',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 19, 16, 54, 41, 756546)),
        ),
    ]
