# Generated by Django 4.1.3 on 2022-11-20 00:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cherooms', '0012_alter_historialbusqueda_fecha_busqueda'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfiluser',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='historialbusqueda',
            name='fecha_busqueda',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 19, 18, 33, 42, 270452)),
        ),
    ]
