# Generated by Django 4.1.3 on 2022-11-20 00:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cherooms', '0018_alter_historialbusqueda_fecha_busqueda'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfiluser',
            name='juan',
            field=models.CharField(default='hola mundo', max_length=100),
        ),
        migrations.AlterField(
            model_name='historialbusqueda',
            name='fecha_busqueda',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 19, 18, 53, 42, 509958)),
        ),
    ]
