# Generated by Django 4.1.3 on 2022-11-20 00:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cherooms', '0019_perfiluser_juan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfiluser',
            name='juan',
        ),
        migrations.AddField(
            model_name='perfiluser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='historialbusqueda',
            name='fecha_busqueda',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 19, 18, 56, 35, 439927)),
        ),
    ]
