# Generated by Django 4.1.3 on 2022-11-20 00:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cherooms', '0020_remove_perfiluser_juan_perfiluser_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfiluser',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='historialbusqueda',
            name='fecha_busqueda',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 19, 18, 57, 19, 839654)),
        ),
    ]
