# Generated by Django 4.1.3 on 2022-11-20 01:17

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cherooms', '0024_rename_is_superuser_perfiluser_admin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfiluser',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='perfiluser',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='perfiluser',
            name='password',
        ),
        migrations.RemoveField(
            model_name='perfiluser',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='perfiluser',
            name='usuario_administrador',
        ),
        migrations.AddField(
            model_name='perfiluser',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historialbusqueda',
            name='fecha_busqueda',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 19, 19, 17, 35, 127557)),
        ),
    ]
