# Generated by Django 4.1.3 on 2022-11-27 05:51

import cherooms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cherooms', '0025_remove_perfiluser_admin_remove_perfiluser_last_login_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciudad',
            name='nombre_ciudad',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='historialbusqueda',
            name='fecha_busqueda',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='perfiluser',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to=cherooms.models.perfil_directory_path),
        ),
        migrations.DeleteModel(
            name='ListaFotos',
        ),
    ]
