# Generated by Django 4.1.3 on 2022-11-28 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cherooms', '0027_foto_publi_alquiler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheros',
            name='favorito_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorito', to='cherooms.perfiluser'),
        ),
        migrations.AlterField(
            model_name='cheros',
            name='perfil_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to='cherooms.perfiluser'),
        ),
        migrations.AlterField(
            model_name='ciudad',
            name='departamento',
            field=models.ForeignKey(db_column='departamento_id', on_delete=django.db.models.deletion.CASCADE, to='cherooms.departamento'),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='pais',
            field=models.ForeignKey(db_column='pais_id', on_delete=django.db.models.deletion.CASCADE, to='cherooms.pais'),
        ),
        migrations.AlterField(
            model_name='foto',
            name='publi_alquiler',
            field=models.ForeignKey(blank=True, db_column='publicacion_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='cherooms.publicacionalquiler'),
        ),
        migrations.AlterField(
            model_name='historialbusqueda',
            name='perfil',
            field=models.ForeignKey(db_column='perfil_id', on_delete=django.db.models.deletion.CASCADE, to='cherooms.perfiluser'),
        ),
        migrations.AlterField(
            model_name='listaamenidad',
            name='amenidad',
            field=models.ForeignKey(db_column='amenidad_id', on_delete=django.db.models.deletion.CASCADE, to='cherooms.amenidad'),
        ),
        migrations.AlterField(
            model_name='listaamenidad',
            name='publicacion',
            field=models.ForeignKey(db_column='publicacion_id', on_delete=django.db.models.deletion.CASCADE, to='cherooms.publicacionalquiler'),
        ),
        migrations.AlterField(
            model_name='listadohobbies',
            name='hobbie',
            field=models.ForeignKey(db_column='hobbie_id', on_delete=django.db.models.deletion.CASCADE, to='cherooms.hobbie'),
        ),
        migrations.AlterField(
            model_name='listadohobbies',
            name='perfil',
            field=models.ForeignKey(db_column='perfil_id', on_delete=django.db.models.deletion.CASCADE, to='cherooms.perfiluser'),
        ),
        migrations.AlterField(
            model_name='listapreferencia',
            name='perfil',
            field=models.ForeignKey(db_column='perfil_id', on_delete=django.db.models.deletion.CASCADE, to='cherooms.perfiluser'),
        ),
        migrations.AlterField(
            model_name='listapreferencia',
            name='preferencia',
            field=models.ForeignKey(db_column='preferencia_id', on_delete=django.db.models.deletion.CASCADE, to='cherooms.preferencia'),
        ),
        migrations.AlterField(
            model_name='perfiluser',
            name='ciudad',
            field=models.ForeignKey(blank=True, db_column='ciudad_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='cherooms.ciudad'),
        ),
        migrations.AlterField(
            model_name='publicacionalquiler',
            name='perfil',
            field=models.ForeignKey(db_column='perfil_id', on_delete=django.db.models.deletion.CASCADE, to='cherooms.perfiluser'),
        ),
        migrations.AlterField(
            model_name='ventaalquiler',
            name='perfil',
            field=models.ForeignKey(db_column='perfil_id', on_delete=django.db.models.deletion.CASCADE, to='cherooms.perfiluser'),
        ),
        migrations.AlterField(
            model_name='ventaalquiler',
            name='publicacion',
            field=models.ForeignKey(db_column='publicacion_id', on_delete=django.db.models.deletion.CASCADE, to='cherooms.publicacionalquiler'),
        ),
    ]
