# Generated by Django 4.0.5 on 2022-12-04 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cherooms', '0029_perfiluser_foto64'),
        ('cherooms', '0029_perfiluser_necesita_cuarto'),
    ]

    operations = [
    ]
