# Generated by Django 4.0.5 on 2022-12-04 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cherooms', '0030_merge_20221204_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='foto',
            name='foto64',
            field=models.CharField(blank=True, max_length=1000000, null=True),
        ),
        migrations.AlterField(
            model_name='perfiluser',
            name='foto64',
            field=models.CharField(blank=True, default='', max_length=1000000, null=True),
        ),
    ]
