# Generated by Django 4.0.3 on 2022-06-16 12:51

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('rol', models.CharField(max_length=15)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Aduana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Carga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=250)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('codigo_departamento', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('nombre_departamento', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.CharField(max_length=15)),
                ('nombre', models.CharField(max_length=30)),
                ('correo', models.EmailField(max_length=254)),
                ('direccion', models.CharField(max_length=70)),
                ('telefono', models.CharField(max_length=15)),
                ('rubro', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido', models.CharField(max_length=30)),
                ('doc_identificacion', models.CharField(max_length=30)),
                ('licencia', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=30)),
                ('estado_motorista', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionTransporte.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_pais', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroTransito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_registro', models.IntegerField()),
                ('origen', models.CharField(max_length=150)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('fecha_destino', models.DateField()),
                ('tipo_de_viaje', models.CharField(max_length=20)),
                ('aduana_destino', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='gestionTransporte.aduana')),
                ('carga', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestionTransporte.carga')),
                ('empresa_dueña', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestionTransporte.empresa')),
                ('motorista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionTransporte.motorista')),
                ('pais_consignatario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestionTransporte.pais')),
            ],
        ),
        migrations.CreateModel(
            name='Sexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_sexo', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoValidacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_validacion', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=30)),
                ('modelo', models.CharField(max_length=30)),
                ('placa', models.CharField(max_length=30)),
                ('anio', models.IntegerField()),
                ('motor', models.CharField(max_length=30)),
                ('chasis', models.CharField(max_length=30)),
                ('num_ejes', models.IntegerField()),
                ('capacidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionTransporte.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Validacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_validacion', models.CharField(max_length=50)),
                ('fecha_validacion', models.DateField(auto_now_add=True)),
                ('aduana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionTransporte.aduana')),
                ('registro_transito', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='gestionTransporte.registrotransito')),
            ],
        ),
        migrations.AddField(
            model_name='registrotransito',
            name='validacion_llave',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='gestionTransporte.validacion'),
        ),
        migrations.AddField(
            model_name='registrotransito',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionTransporte.vehiculo'),
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('codigo_municipio', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('nombre_municipio', models.CharField(max_length=100)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestionTransporte.departamento')),
            ],
        ),
        migrations.AddField(
            model_name='motorista',
            name='sexo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestionTransporte.sexo'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='pais',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='gestionTransporte.pais'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='tipo_documento_empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestionTransporte.tipodocumento'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='usuario_sistema',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='DetalleRegistroValidacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_validacion', models.CharField(max_length=250)),
                ('tipo_validacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestionTransporte.tipovalidacion')),
                ('validacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestionTransporte.validacion')),
            ],
        ),
        migrations.AddField(
            model_name='aduana',
            name='municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestionTransporte.municipio'),
        ),
        migrations.AddField(
            model_name='aduana',
            name='usuario_sistema',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
