# Generated by Django 4.0.3 on 2022-06-16 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionTransporte', '0002_validacion_diferencia_de_peso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='validacion',
            name='diferencia_de_peso',
        ),
    ]
