# Generated by Django 4.0.3 on 2022-06-16 13:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionTransporte', '0003_remove_validacion_diferencia_de_peso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aduana',
            name='usuario_sistema',
        ),
        migrations.AddField(
            model_name='aduana',
            name='usuario_sistema',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
