# Generated by Django 4.0.3 on 2022-06-16 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionTransporte', '0004_remove_aduana_usuario_sistema_aduana_usuario_sistema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrotransito',
            name='validacion_llave',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionTransporte.validacion'),
        ),
        migrations.AlterField(
            model_name='validacion',
            name='aduana',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='gestionTransporte.aduana'),
        ),
    ]
