# Generated by Django 4.0.3 on 2022-06-16 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionTransporte', '0005_alter_registrotransito_validacion_llave_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AduanaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aduana_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestionTransporte.aduana')),
                ('usuario_sistema_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
