# Generated by Django 4.0.3 on 2022-06-16 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionTransporte', '0006_aduanausuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validacion',
            name='fecha_validacion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
