# Generated by Django 4.1.1 on 2022-10-26 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_costo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoja_mano_obra',
            name='numero_hora',
            field=models.FloatField(blank=True, null=True, verbose_name='salario_cargo'),
        ),
        migrations.AddField(
            model_name='hoja_mano_obra',
            name='salario_hora',
            field=models.FloatField(blank=True, null=True, verbose_name='salario_hora'),
        ),
        migrations.AlterField(
            model_name='hoja_mano_obra',
            name='cantidad_cargo',
            field=models.IntegerField(blank=True, null=True, verbose_name='cantidad_cargo'),
        ),
    ]
