# Generated by Django 4.1.1 on 2022-10-26 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_costo', '0003_remove_proyecto_id_hoja_mano_obra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='costosindirectos',
            name='id_proyecto',
        ),
    ]
