# Generated by Django 4.1.1 on 2022-11-05 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_costo', '0005_costosindirectos_descripcion_tasa_indirecta'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoja_mano_obra',
            name='es_costo_real',
            field=models.BooleanField(default=1, verbose_name='es_costo_real'),
            preserve_default=False,
        ),
    ]
